### ISSUE TITLE
Timeout seems to be in multiples of 10

### ISSUE THREAD

**Issue by jlw4049** [rmartin16/qbittorrent-api#155]
### Describe the bug

When I set `requests_args={'timeout': 1}` it takes 10 seconds to stop trying.

So setting it to something like `requests_args={'timeout': 4}` would take 40 seconds. Is this intended?  

### Steps to reproduce

requests_args={'timeout': 1}

### Expected behavior

For this to only take 1 second

### Environment

- Operating System: Windows 10
- Python version: Version 3.10
- Software versions:
  - qBittorrent: Latest
  - qbittorrent-api: Latest

**Comment by rmartin16** [comment]
Hmm....i wouldn't expect it to take 10x longer....but there are automatic retries built in to `qbittorrent-api` (for better or worse).

Are you able to initialize `logging` to `DEBUG` logging and post the output?

During my own testing. I use something like this:
```python
import logging
logging.basicConfig(
     level=logging.DEBUG, 
     format='[%(asctime)s] %(name)s:%(lineno)d %(levelname)s - %(message)s',
     datefmt='%H:%M:%S'
 )
```

**Comment by rmartin16** [comment]
After some experimenting myself and looking through things:

The reality currently is that passing `requests_args={'timeout': 1}` will not mean "do not attempt this API request for longer than 1 second". It means that any HTTP call made with `requests` will receive a `timeout` of 1 second.

Although, it should be [noted](https://requests.readthedocs.io/en/latest/user/quickstart/#timeouts) that even this does _not_ mean "do not spend longer than 1 second on this specific HTTP call"; it means that various timeouts will be set to 1 second....but because of how everything shakes out, the HTTP call could still never actually even finish. For instance, if the server sends _some_ data less than every 1 second after connecting, the connection could be kept alive indefinitely. A lot of people have [ruminated](https://stackoverflow.com/questions/21965484/timeout-for-python-requests-get-entire-response) on this, though.

As for `qbittorrent-api`, the number of HTTP calls made for any one API method call is indeterminate mostly because re-authentication with qBittorrent could be necessary at any time, the connection may be re-initialized for other reasons, and over time some of the implementation has required making multiple HTTP calls for one API call.

So, for many of the same reasons that `requests` themselves did not add this functionality, I am unlikely to either. However, there are third party packages that can ensure a block of code doesn't run longer than a certain amount of wall time. Feel free to let me know if you have other questions or issues, though.

**Comment by jlw4049** [comment]
Thanks bud! I appreciate it.
