### ISSUE TITLE
Feature request: Return torrent hash on add()

### ISSUE THREAD

**Issue by insoIite** [rmartin16/qbittorrent-api#33]
Hello :) 
First of all thanks a lot for your API, it roxx ! 

I'm having a use-case where I want to:

* add torrent to qbitorrent
* track that the torrent is complete
* download the torrent

Right now adding a torrent returns "Ok." or "Fail". therefore I cannot track the current torrent that have been added.

I have a way of fixing my use-case with

```
src = '%s/%s' % (self.torrent_folder, filename)
t_name = re.sub('\.torrent$', '', filename)
client.add_torrent(src); # client is an instance of a custom class that abstract the API

for torrent in client.torrents.info.all():
    if torrent.name != t_name:
        continue
...
```
But having a condition on the torrent name is not really secure/safe/proper/beautiful/... ^^ :(

Would it be possible to retrieve the torrent hash in the response of the torrent_add function ?

Goal would be:

```
src = '%s/%s' % (self.torrent_folder, filename)
hash = client.add_torrent(src);

# dirty code example
while True:
  if complete(hash):
      break
...
```
There is one thing I don't understand in the code, the return of `torrents_add` is supposed to be `requests.request` response where there should have a lot of data available in the response no ?

**Comment by rmartin16** [comment]
Yeah, I agree; returning something to indicate which torrent was added would be beneficial. However, this is unfortunately more a function of qBittorrent than this API client....since it is qBittorrent that's only returning "Ok." or "Fail.".

I've considered how to return information about the torrent that was added but there isn't really a reliable way to do that. For one, you can add many torrents at once. But really, the problem is that you can pass objects to client.torrents_add() that provide only indirect information about what torrents should be added; for example, a file handle or a random URL.

I think that until qbittorrent/qbittorrent#4879 is addressed.....that will remain a nuisance....although, I'm definitely open to seeing anyone's ideas :)

**Comment by insoIite** [comment]
Yeah, I thought aswell that it would be on qbitorrent side :/ 


for the use case above about adding multiple torrents at once,
the add_torrent could return [{filename: "foo.torrent", hash:  $hash}] for example (just thinking while writing)

Anyway, thanks a lot for you work :)
