### ISSUE TITLE
Adding RSS feeds fails without specifying the path

### ISSUE THREAD

**Issue by ProchyGaming** [rmartin16/qbittorrent-api#422]
### Describe the bug

I'm not quite sure if I had misunderstood the docs, but i think the path is an optional parameter and yet if you run it without it it throws an `qbittorrentapi.exceptions.MissingRequiredParameters400Error`

### Steps to reproduce

execute rss.addFeed without specifying the path, e. g. `qbittorrent_client.rss.addFeed(url=rss_feed_url) `

### Expected behavior

Adds RSS feed without any issues

### Environment

- Operating System: Windows 11
- Python version: 3.12.2 (64-bit)
- Software versions:
  - qBittorrent: 4.4.1
  - qbittorrent-api: 2.8.5

### Additional context

If the the command `qbittorrent_client.rss.addFeed(url=rss_feed_url)` is ran like this `qbittorrent_client.rss.addFeed(url=rss_feed_url, item_path='')` the command runs without any issues.

I would also like to state that my WebUI is running on Xubuntu using qbittorrent-nox, but I am not sure if that is the root of the problem.

**Comment by rmartin16** [comment]
Ahh, I see; the actual [implementation](https://github.com/qbittorrent/qBittorrent/blob/dc501c39bee1c0bf8ecea66e9e6c377727b33c33/src/webui/api/rsscontroller.cpp#L58) of `rss/addFeed` requires the `path` parameter to actually be included....but if it's empty, it defaults to using the URL as the path for the feed.

So, given this is currently an error, it should be fine to change the default to `""` instead of `None` so this defaulting behavior occurs.

**Comment by rmartin16** [comment]
Thanks for letting know, @ProchyGaming. Fix released in [v2024.2.59](https://pypi.org/project/qbittorrent-api/2024.2.59/).
