### ISSUE TITLE
torrent.add_trackers(urls=to_add) can add invalid tracker

### ISSUE THREAD

**Issue by 1aam2am1** [rmartin16/qbittorrent-api#432]
### Describe the bug

for torrent in qbt_client.torrents.info.all():
    torrent.add_trackers(urls="tracker_with_|_symbol")

Function doesn't have a validation, and can add a tracker with invalid symbol '|', this creates problem as it is impossible to remove.

### Steps to reproduce

1. Create conn_info
2. Connect to qbittorrent
3. Add new tracker with invalid symbol
4. You can't remove the tracker

### Expected behavior

Function will throw with error message stating that '|' symbol is invalid.

### Environment

- Operating System: wsl2
- Python version: Python 3.10.12
- Software versions:
  - qBittorrent: v4.6.3
  - qBittorrent Web API: 2.9.3
  - bitness: 64
  - boost: 1.82.0
  - libtorrent: 2.0.10.0
  - openssl: 3.1.5
  - qt: 6.6.1
  - zlib: 1.3.1

**Comment by rmartin16** [comment]
Thanks for reporting this. While I agree this is a less than ideal situation, I have avoided trying to enforce much if any validation in this client. This is most notable in API endpoint parameters that are required but this client will happily omit them. This is mostly because I didn't want to have to figure out each endpoint's limits and then encode them here...but also because the requirements can change from one API version to another and that makes it difficult for this client to support arbitrary versions of qBittorrent.

On that basis, I am closing this issue but encourage you to report it to [qBittorrent](https://github.com/qbittorrent/qBittorrent/issues) so they can resolve at the source.
