### ISSUE TITLE
Client connect block forever 

### ISSUE THREAD

**Issue by mengyyy** [rmartin16/qbittorrent-api#46]
Hello, I use this lib to connect a qbt client but its  network is unstable, and the client block forever,.
Could I add `timeout` in the requests?
Thank you.

**Comment by rmartin16** [comment]
Hey @mengyyy, thanks for bringing this up....i had forgotten to consider that Requests will just wait forever in certain cases.

Strictly speaking, this is already possible...mostly. All of the API calls support additional keyword arguments to fine tune how any individual API call is made. For instance, to add a `timeout`:

```python
http_timeout = (9.05, 30)
client.torrents_add(url='abc.xyz/magnet', requests_params={'timeout', http_timeout})
client.torrents_info(requests_params={'timeout', http_timeout})
```

This can be a little tedious, though, since it needs to be specified for each API call. So, similar to how `Client` can be instantiated with `EXTRA_HEADERS` to allow user-specified headers to be included in all API calls, I can add something like `SESSION_PARAMS` so that the entire configuration of the Requests Session is exposed to users.

Finally. there is one HTTP request that you cannot add a timeout to right now. During the initial connection to qBittorrent, a HTTP HEAD request is made to determine whether the connection is using TLS or not. So, I'll apply this new timeout logic there as well.

**Comment by mengyyy** [comment]
This example code solved my problem.
